server:
  port: 8080
  servlet:
    context-path: /gateway

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/registry/eureka

spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: crud
          uri: lb://crud
          predicates:
            - Path=/crud/**

        - id: pagamento
          uri: lb://pagamento
          predicates:
            - Path=/pagamento/**

        - id: auth
          uri: lb://auth
          predicates:
            - Path=/auth/**

