server:
  port: 8083
  servlet:
    context-path: /auth

spring:
  application:
    name: auth
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialiect
  jmx:
    enabled: false
  datasource:
    url: jdbc:mysql://db4free.net:3306/micro_auth?allowPublicKeyRetrieval=true&sslMode=DISABLED&useSSL=false&serverTimezone=UTC
    username: admin_auth
    password: 'aAsgegqvGaeK4Z_'

security:
  jwt:
    secret-key: chave_microservices
    expire-length: 360000

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/registry/eureka
